services:

  db:
    build:
      context: . 
      dockerfile: ./data_ingestion/Dockerfile.db 
    ports:
      - "5432:5432"
    container_name: postgres_dbvector      
    environment:
      POSTGRES_DB: medquad_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d # estensione vector
  
  data_ingestion: 
    build:
      context: . 
      dockerfile: ./data_ingestion/Dockerfile 
    container_name: data_ingestion
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db 
      POSTGRES_PORT: 5432
    depends_on:
      - db 

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    container_name: ollama      
    volumes:
      - ollama_data:/root/.ollama

  backend: 
    build:
      context: .
      dockerfile: ./backend/Dockerfile 
    ports:
      - "8000:8000"
    container_name: backend      
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db 
      POSTGRES_PORT: 5432
      OLLAMA_BASE_URL: http://ollama:11434 
      OLLAMA_MODEL_NAME: ${OLLAMA_MODEL_NAME}
    depends_on:
      - db
      - ollama
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "8080:80"  
      container_name: frontend               
      depends_on:
        - db                      
      environment:
        - API_URL=http://backend:8000


volumes:
  db_data:
  ollama_data: