# FROM postgres:16

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     build-essential \
#     postgresql-server-dev-16 \
#     git \
#     && rm -rf /var/lib/apt/lists/*

# RUN git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git /usr/src/pgvector \
#     && cd /usr/src/pgvector \
#     && make \
#     && make install

FROM postgres:16

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    postgresql-server-dev-16 \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git /usr/src/pgvector \
    && cd /usr/src/pgvector \
    && make \
    && make install

###RUN apt-get remove -y build-essential git postgresql-server-dev-16 && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 5432